---

- hosts: all
  become: true
  tasks:

  - name: Install Updates
    apt:
      upgrade: dist
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

  - name: Install required packages
    apt:
      name: tcpdump
      state: present
    when: ansible_distribution == "Ubuntu"

  - name: Extract executable from PCAP
    copy:
      src: nimda.download.pcap
      dest: /pcap
